# Generated by Django 4.0.4 on 2022-10-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_project_autors_remove_project_full_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year_of_creating',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='Random project', max_length=127, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(null=True, to='main.suser'),
        ),
    ]
