# Generated by Django 4.0.4 on 2022-10-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_suser_remove_project_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(to='main.suser'),
        ),
    ]
